<?php

function sum_menu() {
    $items = array();
    $items['sum'] = array(
        'title' => 'Calculate Sum',
        'page callback' => 'drupal_get_form',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'page arguments' => array('sum_form'),
    );
    $items['success'] = array(
        'title' => 'Success',
        'access callback' => TRUE,
        'page callback' => 'sum_success',
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function sum_form() {
    $form = array();
    $form['left_number'] = array(
        '#title' => 'Left Number',
        '#type' => 'textfield',
        '#description' => t('please enter your starting number'),
    );
    $form['right_number'] = array(
        '#title' => 'Left Number',
        '#type' => 'textfield',
        '#description' => t('please enter a number to add to the starting number'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate Sum',
    );
    return $form;
}

function sum_form_submit($form, &$form_state) {
    $first_number = $form_state['values']['left_number'];
    $second_number = $form_state['values']['right_number'];
    $sum = $first_number + $second_number;
    $_SESSION['sum'] = $sum;
    $form_state['redirect'] = 'success';

}

function sum_success() {
    $answer = $_SESSION['sum'];
    return "The sum of your numbers is $answer";
}