# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
